import legal from './legal'

export default {

  'item.document.fi': 'Dokumentti',
  'item.document.sv': 'Dokument',
  'item.note.fi': 'Muistio',
  'item.note.sv': 'Memo',
  'item.textblock.fi': 'Tekstikenttä',
  'item.textblock.sv': 'Textfält',
  'item.heading.fi': 'Otsikko',
  'item.heading.sv': 'Rubrik',
  'item.arrow.fi': 'Nuoli',
  'item.arrow.sv': 'Pil',

  'label.welcome.fi': 'Yhteistyöalusta',
  'label.welcome.sv': 'Samarbetsplattform',
  'label.login.fi': 'Kirjautuminen',
  'label.login.sv': 'Inloggning',
  'label.forgot_password.fi': 'Salasana unohtunut?',
  'label.forgot_password.sv': 'Glömt lösenord',
  'label.reset_password.fi': 'Vaihda salasana',
  'label.reset_password.sv': 'Ändra lösenord',
  'label.email_sent.fi': 'Sähköposti lähetetty',
  'label.email_sent.sv': 'E-postmeddelandet skickades',
  'label.to.fi': 'osoitteeseen',
  'label.to.sv': 'till adressen',
  'label.user_profile.fi': 'Käyttäjäprofiili',
  'label.user_profile.sv': 'Användarprofil',
  'label.show_email_address.fi': 'Näytä sähköpostiosoite muille käyttäjille',
  'label.show_email_address.sv': 'Visa e-postadressen till andra användare',
  'label.privacy.fi': 'Yksityisyys',
  'label.privacy.sv': 'Avskildhet',
  'label.imprint.fi': 'Impressum',
  'label.imprint.sv': 'Impressum',
  'label.privacy_policy.fi': 'Tietosuoja',
  'label.privacy_policy.sv': 'Dataskydd',
  'label.shared_workspace.fi': 'Jaettu työtila',
  'label.shared_workspace.sv': 'Gemensam arbetsyta',
  'label.admin.fi': 'Yhteistyöalusta - hallinta',
  'label.admin.sv': 'Samarbetsplattform - Administrering',
  'label.admin_workspaces.fi': 'Työtilat ja jäsenet',
  'label.admin_workspaces.sv': 'Arbetsytor och medlemmar',
  'label.admin_users.fi': 'Käyttäjät ja jäsenyydet',
  'label.admin_users.sv': 'Användare och medlemskap',
  'label.no_workspaces.fi': 'Ei työtiloja saatavilla',
  'label.no_workspaces.sv': 'Inga lediga arbetsytor',
  'label.discussion.fi': 'Keskustelu',
  'label.discussion.sv': 'Diskussion',
  'label.no_comments.fi': 'Ei keskusteluja<br>Aloita',
  'label.no_comments.sv': 'Inga discussioner<br>Starta!',
  'label.document_filter.fi': 'järjestys: dokumentti',
  'label.document_filter.sv': 'upplägg: dokument',
  'label.textblock_filter.fi': 'järjestys: tekstikenttä',
  'label.textblock_filter.sv': 'järjestys: textfält',
  'label.document_name.fi': 'Dokumentin nimi',
  'label.document_name.sv': 'Dokument namn',
  'label.file.fi': 'Tiedosto',
  'label.file.sv': 'Fil',
  'label.translation.fi': 'Käännös',
  'label.translation.sv': 'Översättning',
  'label.translation_edited.fi': 'Muokattu käännös',
  'label.translation_edited.sv': 'Redigerad översättning',
  'label.automatic.fi': 'automaattinen',
  'label.automatic.sv': 'automatisk',
  'label.edited.fi': 'muokattu',
  'label.edited.sv': 'redigerad',
  'label.none.fi': 'ei mitään',
  'label.none.sv': 'ingen',
  'label.new_comment.fi': 'Uusi dokumentti',
  'label.new_comment.sv': 'Ny dokument',
  'label.new_comment_document.fi': 'Uusi lisäys dokumenttiin',
  'label.new_comment_document.sv': 'Nytt tillägg till dokumentet',
  'label.new_comment_textblock.fi': 'Uusi lisäys tekstikenttään',
  'label.new_comment_textblock.sv': 'Nytt tillägg till textälftet',
  'label.new_note.fi': 'Uusi muistio',
  'label.new_note.sv': 'Ny memo',
  'label.new_textblock.fi': 'Uusi Tekstikenttä',
  'label.new_textblock.sv': 'Ny Textälft',
  'label.new_label.fi': 'Uusi otsikko',
  'label.new_label.sv': 'Ny rubrik',
  'label.new_workspace.fi': 'Uusi työtila',
  'label.new_workspace.sv': 'Ny arbetsyta',
  'label.new_user.fi': 'Uusi käyttäjä',
  'label.new_user.sv': 'Ny användare',
  'label.edit_workspace.fi': 'Muokkaa työtilaa',
  'label.edit_workspace.sv': 'Redigera arbetsyta',
  'label.edit_user.fi': 'Muokkaa käyttäjää',
  'label.edit_user.sv': 'Redigera användare',
  'label.edit_memberships.fi': 'Hallinnoi jäseniä',
  'label.edit_memberships.sv': 'Administrera medlemmar',
  'label.edit_affiliations.fi': 'Hallinnoi jäsenyyksiä',
  'label.edit_affiliations.sv': 'Administrera medlemskap',
  'label.workspace.fi': 'Työtila',
  'label.workspace.sv': 'Arbetsyta',
  'label.owner.fi': 'Omistaja',
  'label.owner.sv': 'Ägare',
  'label.user.fi': 'Käyttäjä',
  'label.user.sv': 'Användare',
  'label.active.fi': 'Aktivinen',
  'label.active.sv': 'Aktiv',
  'label.member.fi': 'Jäsen',
  'label.member.sv': 'Medlem',
  'label.editor.fi': 'Editori',
  'label.editor.sv': 'Editor',
  'label.workspace_name.fi': 'Nimi',
  'label.workspace_name.sv': 'Namn',
  'label.display_name.fi': 'Nimi',
  'label.display_name.sv': 'Namn',
  'label.email_address.fi': 'Sähköposti',
  'label.email_address.sv': 'E-post',
  'label.password.fi': 'Salasana',
  'label.password.sv': 'Lösenord',
  'label.color.fi': 'Väri',
  'label.color.sv': 'Färg',
  'label.search.fi': 'Hae',
  'label.search.sv': 'Sök',
  'label.of.fi': '-',
  'label.of.sv': 'av',
  'label.warning.fi': 'Varoitus',
  'label.warning.sv': 'Varning',

  'action.submit.fi': 'OK',
  'action.submit.sv': 'OK',
  'action.cancel.fi': 'Peruuta',
  'action.cancel.sv': 'Avbryt',
  'action.reply.fi': 'Vastaus',
  'action.reply.sv': 'Svar',
  'action.create.fi': 'Luo',
  'action.create.sv': 'Skapa',
  'action.edit.fi': 'Muokkaa',
  'action.edit.sv': 'Redigera',
  'action.lock.fi': 'Lukitse',
  'action.lock.sv': 'Låsa',
  'action.unlock.fi': 'Avaa',
  'action.unlock.sv': 'Öppna',
  'action.delete.fi': 'Poista',
  'action.delete.sv': 'Radera',
  'action.delete_many.fi': 'Poista ${} kohteet',
  'action.delete_many.sv': 'Radera ${} objekt',
  'action.download.fi': 'Lataa',
  'action.download.sv': 'Ladda ner',
  'action.translate.fi': 'Käännä',
  'action.translate.sv': 'Översätt',
  'action.set_zoom.fi': 'Aseta zoom',
  'action.set_zoom.sv': 'Ange zoom',
  'action.add_workspace.fi': 'Lisää työtila',
  'action.add_workspace.sv': 'Lägg till arbetsyta',
  'action.add_user.fi': 'Lisää käyttäjä',
  'action.add_user.sv': 'Lägg till användare',
  'action.show_workspace.fi': 'Näytä työtila',
  'action.show_workspace.sv': 'Visa arbetsyta',
  'action.edit_workspace.fi': 'Muokkaa työtilaa',
  'action.edit_workspace.sv': 'Redigera arbetsytan',
  'action.edit_memberships.fi': 'Hallinnoi jäseniä',
  'action.edit_memberships.sv': 'Administrera medlemmar',
  'action.edit_user.fi': 'Muokkaa käyttäjää',
  'action.edit_user.sv': 'Redigera användare',
  'action.edit_affiliations.fi': 'Hallinnoi jäsenyyksiä',
  'action.edit_affiliations.sv': 'Administrera medlemskap',
  'action.delete_workspace.fi': 'Poista työtila',
  'action.delete_workspace.sv': 'Radera arbetsytan',
  'action.delete_user.fi': 'Poista käyttäjä',
  'action.delete_user.sv': 'Radera användare',
  'action.reset_password.fi': 'Palauta salasana',
  'action.reset_password.sv': 'Återställ lösenord',
  'action.change_password.fi': 'Vaihda salasana',
  'action.change_password.sv': 'Ändra lösenord',

  'tooltip.add.fi': 'Lisää',
  'tooltip.add.sv': 'Lägg till',
  'tooltip.home.fi': 'Koti',
  'tooltip.home.sv': 'Hem',
  'tooltip.zoom_to_fit.fi': 'Sovita',
  'tooltip.zoom_to_fit.sv': 'Passa',
  'tooltip.zoom_in.fi': 'Suurenna',
  'tooltip.zoom_in.sv': 'Förstora',
  'tooltip.zoom_out.fi': 'Pienennä',
  'tooltip.zoom_out.sv': 'Minska',
  'tooltip.discuss.fi': 'Keskustelu',
  'tooltip.discuss.sv': 'Diskussion',
  'tooltip.submit.fi': 'Lähetä',
  'tooltip.submit.sv': 'Skicka',
  'tooltip.reply.fi': 'Vastaa',
  'tooltip.reply.sv': 'Svar',
  'tooltip.translate.fi': 'Käännä',
  'tooltip.translate.sv': 'Översätta',
  'tooltip.attach.fi': 'Liitä',
  'tooltip.attach.sv': 'Inkludera',
  'tooltip.reset_filter.fi': 'Tyhjennä valinnat',
  'tooltip.reset_filter.sv': 'Radera urvalen',
  'tooltip.open_panel.fi': 'Avaa keskustelu',
  'tooltip.open_panel.sv': 'Öppna diskussion',
  'tooltip.close_panel.fi': 'Sulje keskustelu',
  'tooltip.close_panel.sv': 'Avsluta diskussion',
  'tooltip.open_fullscreen.fi': 'Avaa koko näytölle',
  'tooltip.open_fullscreen.sv': 'Öppna fullskärm',
  'tooltip.close_fullscreen.fi': 'Sulje kokonäyttö',
  'tooltip.close_fullscreen.sv': 'Avstäng fullskärm',
  'tooltip.select_workspace.fi': 'Valitse työtila',
  'tooltip.select_workspace.sv': 'Välj arbetsyta',
  'tooltip.select_language.fi': 'Valitse kieli',
  'tooltip.select_language.sv': 'Välj språk',
  'tooltip.admin.fi': 'Hallinta',
  'tooltip.admin.sv': 'Administration',

  'warning.delete.fi': 'Aiot poistaa tämän kohteen',
  'warning.delete.sv': 'Du kommer att radera detta objekt',
  'warning.delete_many.fi': 'Olet poistamassa ${} kohdetta',
  'warning.delete_many.sv': 'Du kommer att radera ${} objets',
  'warning.delete_comment.fi': 'Olet poistamassa näutä kommentteja',
  'warning.delete_comment.sv': 'Du kommer att radera denna kommentar',
  'warning.delete_workspace.fi': 'Olet poistamassa tämän työtilan',
  'warning.delete_workspace.sv': 'Du kommer att radera denna arbetsyta',
  'warning.delete_user.fi': 'Olet poistamassa tämän käyttäjän',
  'warning.delete_user.sv': 'Du kommer att radera denna användare',
  'warning.translation_failed.fi': 'Automaattinen käännös epäonnistui',
  'warning.translation_failed.sv': 'Automatisk översättning misslyckades',
  'warning.translation_confirm.fi': `Syötettäsi ei voitu kääntää. Jatka muokkausta napsauttamalla "Peruuta" tai
    tai "Luo" tallentaaksesi ilman kääntämistä.`,
  'warning.translation_confirm.sv': `Din text kunde inte översättas. Fortsätt redigera genom att klicka på "Avbryt" eller
    eller "Skapa" för att spara utan att översätta.`,
  'warning.translation_alert.fi': 'Tekstiäsi ei voitu kääntää.',
  'warning.translation_alert.sv': 'Din text kunde inte översättas.',

  ...legal
}
