import legal from './legal'

export default {

  'item.document.fi': 'Dokument',
  'item.document.sv': 'Document',
  'item.note.fi': 'Notiz',
  'item.note.sv': 'Note',
  'item.textblock.fi': 'Textblock',
  'item.textblock.sv': 'Bloc de texte',
  'item.heading.fi': 'Überschrift',
  'item.heading.sv': 'Titre',
  'item.arrow.fi': 'Pfeil',
  'item.arrow.sv': 'Flèche',

  'label.welcome.fi': 'Online Kollaborationsplattform',
  'label.welcome.sv': 'Plate-forme de collaboration en ligne',
  'label.login.fi': 'Login',
  'label.login.sv': 'Login',
  'label.forgot_password.fi': 'Aktuelles Passwort vergessen?',
  'label.forgot_password.sv': 'Mot de passe actuel oublié?',
  'label.reset_password.fi': 'Passwort zurücksetzen',
  'label.reset_password.sv': 'Réinitialiser le mot de passe',
  'label.email_sent.fi': 'Email erfolgreich gesendet',
  'label.email_sent.sv': 'Email envoyé avec succès',
  'label.to.fi': 'an',
  'label.to.sv': 'à',
  'label.user_profile.fi': 'Benutzerprofil',
  'label.user_profile.sv': 'Profil d\'utilisateur',
  'label.show_email_address.fi': 'Emailadresse anderen Nutzern zeigen',
  'label.show_email_address.sv': 'Montrer son adresse e-mail aux autres utilisateurs',
  'label.privacy.fi': 'Privacy',
  'label.privacy.sv': 'Vie privée',
  'label.imprint.fi': 'Impressum',
  'label.imprint.sv': 'Impressum',
  'label.privacy_policy.fi': 'Datenschutz',
  'label.privacy_policy.sv': 'Protection des données',
  'label.shared_workspace.fi': 'Gemeinsamer Arbeitsbereich',
  'label.shared_workspace.sv': 'Espace de travail commun',
  'label.admin.fi': 'Online Kollaborationsplattform - Verwaltung',
  'label.admin.sv': 'Plate-forme de collaboration en ligne - Administration',
  'label.admin_workspaces.fi': 'Arbeitsbereiche und Mitglieder',
  'label.admin_workspaces.sv': 'Espaces de travail et membres',
  'label.admin_users.fi': 'Benutzer und Mitgliedschaften',
  'label.admin_users.sv': 'Utilisateurs et affiliations',
  'label.no_workspaces.fi': 'Keine Arbeitsbereiche vorhanden',
  'label.no_workspaces.sv': 'Aucun espace de travail disponible',
  'label.discussion.fi': 'Diskussion',
  'label.discussion.sv': 'Discussion',
  'label.no_comments.fi': 'Noch keine Diskussionsbeiträge.<br>Machen Sie den Anfang!',
  'label.no_comments.sv': 'Aucune contribution.<br>Lancez-vous!',
  'label.document_filter.fi': 'nach Dokument gefiltert',
  'label.document_filter.sv': 'filtré par document',
  'label.textblock_filter.fi': 'nach Textblock gefiltert',
  'label.textblock_filter.sv': 'filtré par bloc de texte',
  'label.document_name.fi': 'Dokument Name',
  'label.document_name.sv': 'Nom du document',
  'label.file.fi': 'Datei',
  'label.file.sv': 'Fichier',
  'label.translation.fi': 'Übersetzung',
  'label.translation.sv': 'Traduction',
  'label.translation_edited.fi': 'Übersetzung bearbeitet',
  'label.translation_edited.sv': 'Traduction éditée',
  'label.automatic.fi': 'automatisch',
  'label.automatic.sv': 'automatique',
  'label.edited.fi': 'bearbeitet',
  'label.edited.sv': 'éditée',
  'label.none.fi': 'keine',
  'label.none.sv': 'pas de',
  'label.new_comment.fi': 'Neuer Beitrag',
  'label.new_comment.sv': 'Nouvelle contribution',
  'label.new_comment_document.fi': 'Neuer Beitrag zum Dokument',
  'label.new_comment_document.sv': 'Nouvelle contribution au document',
  'label.new_comment_textblock.fi': 'Neuer Beitrag zum Textblock',
  'label.new_comment_textblock.sv': 'Nouvelle contribution au bloc de texte',
  'label.new_note.fi': 'Neue Notiz',
  'label.new_note.sv': 'Nouvelle Note',
  'label.new_textblock.fi': 'Neuer Textblock',
  'label.new_textblock.sv': 'Nouveau bloc de texte',
  'label.new_label.fi': 'Neue Überschrift',
  'label.new_label.sv': 'Nouveau Titre',
  'label.new_workspace.fi': 'Neuer Arbeitsbereich',
  'label.new_workspace.sv': 'Nouvel espace de travail',
  'label.new_user.fi': 'Neuer Benutzer',
  'label.new_user.sv': 'Nouvel utilisateur',
  'label.edit_workspace.fi': 'Arbeitsbereich bearbeiten',
  'label.edit_workspace.sv': 'Modifier l\'espace de travail',
  'label.edit_user.fi': 'Benutzer bearbeiten',
  'label.edit_user.sv': 'Modifier l\'utilisateur',
  'label.edit_memberships.fi': 'Mitglieder verwalten',
  'label.edit_memberships.sv': 'Gérer les membres',
  'label.edit_affiliations.fi': 'Mitgliedschaften verwalten',
  'label.edit_affiliations.sv': 'Gérer les affiliations',
  'label.workspace.fi': 'Arbeitsbereich',
  'label.workspace.sv': 'Espace de travail',
  'label.owner.fi': 'Eigentümer',
  'label.owner.sv': 'Propriétaire',
  'label.user.fi': 'Benutzer',
  'label.user.sv': 'Utilisateur',
  'label.active.fi': 'Aktiv',
  'label.active.sv': 'Actif',
  'label.member.fi': 'Mitglied',
  'label.member.sv': 'Membre',
  'label.editor.fi': 'Editor',
  'label.editor.sv': 'Éditeur',
  'label.workspace_name.fi': 'Name',
  'label.workspace_name.sv': 'Nom',
  'label.display_name.fi': 'Name',
  'label.display_name.sv': 'Nom',
  'label.email_address.fi': 'Email',
  'label.email_address.sv': 'E-mail',
  'label.password.fi': 'Passwort',
  'label.password.sv': 'Mot de passe',
  'label.color.fi': 'Farbe',
  'label.color.sv': 'Couleur',
  'label.search.fi': 'Suche',
  'label.search.sv': 'Recherche',
  'label.of.fi': 'von',
  'label.of.sv': 'de',
  'label.warning.fi': 'Warnung',
  'label.warning.sv': 'Avertissement',

  'action.submit.fi': 'OK',
  'action.submit.sv': 'OK',
  'action.cancel.fi': 'Abbrechen',
  'action.cancel.sv': 'Annuler',
  'action.reply.fi': 'Antworten',
  'action.reply.sv': 'Réponse',
  'action.create.fi': 'Erstellen',
  'action.create.sv': 'Créer',
  'action.edit.fi': 'Ändern',
  'action.edit.sv': 'Éditer',
  'action.lock.fi': 'Verriegeln',
  'action.lock.sv': 'Verrouiller',
  'action.unlock.fi': 'Entriegeln',
  'action.unlock.sv': 'Déverrouiller',
  'action.delete.fi': 'Löschen',
  'action.delete.sv': 'Supprimer',
  'action.delete_many.fi': '${} Objekte löschen',
  'action.delete_many.sv': 'Supprimer ${} objets',
  'action.download.fi': 'Download',
  'action.download.sv': 'Télécharger',
  'action.translate.fi': 'Übersetzen',
  'action.translate.sv': 'Traduire',
  'action.set_zoom.fi': 'Aktuellen Zoom-Wert speichern',
  'action.set_zoom.sv': 'Enregistrer la valeur actuelle du zoom',
  'action.add_workspace.fi': 'Arbeitsbereich hinzufügen',
  'action.add_workspace.sv': 'Ajouter un espace de travail',
  'action.add_user.fi': 'Benutzer hinzufügen',
  'action.add_user.sv': 'Ajouter un utilisateur',
  'action.show_workspace.fi': 'Arbeitsbereich anzeigen',
  'action.show_workspace.sv': 'Afficher l\'espace de travail',
  'action.edit_workspace.fi': 'Arbeitsbereich bearbeiten',
  'action.edit_workspace.sv': 'Modifier l\'espace de travail',
  'action.edit_memberships.fi': 'Mitglieder verwalten',
  'action.edit_memberships.sv': 'Gérer les membres',
  'action.edit_user.fi': 'Benutzer bearbeiten',
  'action.edit_user.sv': 'Modifier l\'utilisateur',
  'action.edit_affiliations.fi': 'Mitgliedschaften verwalten',
  'action.edit_affiliations.sv': 'Gérer les affiliations',
  'action.delete_workspace.fi': 'Arbeitsbereich löschen',
  'action.delete_workspace.sv': 'Supprimer l\'espace de travail',
  'action.delete_user.fi': 'Benutzer löschen',
  'action.delete_user.sv': 'Supprimer l\'utilisateur',
  'action.reset_password.fi': 'Passwort zurücksetzen',
  'action.reset_password.sv': 'Réinitialiser le mot de passe',
  'action.change_password.fi': 'Passwort ändern',
  'action.change_password.sv': 'Modifier le mot de passe',

  'tooltip.add.fi': 'Element hinzufügen',
  'tooltip.add.sv': 'Ajouter un élément',
  'tooltip.home.fi': 'Startbereich anzeigen',
  'tooltip.home.sv': 'Retour à la zone de départ',
  'tooltip.zoom_to_fit.fi': 'gesamten Arbeitsbereich anzeigen',
  'tooltip.zoom_to_fit.sv': 'Afficher tout l\'espace de travail',
  'tooltip.zoom_in.fi': 'größer zoomen',
  'tooltip.zoom_in.sv': 'zoomer',
  'tooltip.zoom_out.fi': 'kleiner zoomen',
  'tooltip.zoom_out.sv': 'zoomer plus petit',
  'tooltip.discuss.fi': 'Diskussion anzeigen',
  'tooltip.discuss.sv': 'Afficher la discussion',
  'tooltip.submit.fi': 'Beitrag absenden',
  'tooltip.submit.sv': 'Publier la contribution',
  'tooltip.reply.fi': 'Antworten',
  'tooltip.reply.sv': 'Répondre',
  'tooltip.translate.fi': 'Übersetzen',
  'tooltip.translate.sv': 'Traduire',
  'tooltip.attach.fi': 'Dateien anhängen',
  'tooltip.attach.sv': 'Joindre des fichiers',
  'tooltip.reset_filter.fi': 'Filter entfernen',
  'tooltip.reset_filter.sv': 'Supprimer le filtre',
  'tooltip.open_panel.fi': 'Diskussion aufklappen',
  'tooltip.open_panel.sv': 'Ouvrir la discussion',
  'tooltip.close_panel.fi': 'Diskussion zuklappen',
  'tooltip.close_panel.sv': 'Fermer la discussion',
  'tooltip.open_fullscreen.fi': 'Dokument in Vollbild-Ansicht anzeigen',
  'tooltip.open_fullscreen.sv': 'Afficher le document en plein écran',
  'tooltip.close_fullscreen.fi': 'Arbeitsbereich anzeigen',
  'tooltip.close_fullscreen.sv': 'Afficher l\'espace de travail',
  'tooltip.select_workspace.fi': 'Arbeitsbereich wechseln',
  'tooltip.select_workspace.sv': 'Changer d\'espace de travail',
  'tooltip.select_language.fi': 'Sprache auswählen',
  'tooltip.select_language.sv': 'Choisir la langue',
  'tooltip.admin.fi': 'Verwaltung',
  'tooltip.admin.sv': 'Administration',

  'warning.delete.fi': 'Sie sind im Begriff dieses Objekt zu löschen',
  'warning.delete.sv': 'Vous êtes sur le point de supprimer cet objet',
  'warning.delete_many.fi': 'Sie sind im Begriff ${} Objekte zu löschen',
  'warning.delete_many.sv': 'Vous êtes sur le point de supprimer des ${} objets',
  'warning.delete_comment.fi': 'Sie sind im Begriff diesen Kommentar zu löschen',
  'warning.delete_comment.sv': 'Vous êtes sur le point de supprimer ce commentaire',
  'warning.delete_workspace.fi': 'Sie sind im Begriff diesen Arbeitsbereich zu löschen',
  'warning.delete_workspace.sv': 'Vous êtes sur le point de supprimer cet espace de travail',
  'warning.delete_user.fi': 'Sie sind im Begriff diesen Benutzer zu löschen',
  'warning.delete_user.sv': 'Vous êtes sur le point de supprimer cet utilisateur',
  'warning.translation_failed.fi': 'Automatische Übersetzung fehlgeschlagen',
  'warning.translation_failed.sv': 'Échec de la traduction automatique',
  'warning.translation_confirm.fi': `Deine Eingabe konnte nicht übersetzt werden. Klicke "Abbrechen", um weiter zu
    editieren oder "Erstellen", um ohne Übersetzung zu speichern. Tipp: Wähle nach dem Erstellen "Ändern", um eine
    Übersetzung hinzuzufügen.`,
  'warning.translation_confirm.sv': `Ta saisie n'a pas pu être traduite. Clique sur "Annuler" pour continuer à éditer
    ou sur "Créer" pour enregistrer sans traduction. Conseil: après la création, choisis "Éditer" pour ajouter une
    traduction.`,
  'warning.translation_alert.fi': `Deine Eingabe konnte nicht übersetzt werden.`,
  'warning.translation_alert.sv': `Ta saisie n'a pas pu être traduite.`,

  ...legal
}
